import * as fs from 'fs';
import * as path from 'path';

const DEFAULT_RAW_DIR = path.join(__dirname, '../raw');
const DEFAULT_OUTPUT_DIR = path.join(__dirname, '../packages/showcase/src/stories');

interface IconEntry {
  category: string;
  name: string;
  sizes: number[];
}

interface SVGFile {
  category: string;
  name: string;
  size: string;
  fullPath: string;
}

function getSVGFiles(rawDir: string): SVGFile[] {
  const files: SVGFile[] = [];
  const categoryDirs = fs.readdirSync(rawDir);

  for (const category of categoryDirs) {
    const categoryPath = path.join(rawDir, category);
    if (!fs.statSync(categoryPath).isDirectory()) continue;

    const iconDirs = fs.readdirSync(categoryPath);
    for (const iconName of iconDirs) {
      const iconDir = path.join(categoryPath, iconName);
      if (!fs.statSync(iconDir).isDirectory()) continue;

      const svgFiles = fs.readdirSync(iconDir).filter(f => f.endsWith('.svg'));
      for (const svgFile of svgFiles) {
        const match = svgFile.match(/^(.+?)_(\d+)\.svg$/);
        if (match) {
          files.push({
            category,
            name: iconName,
            size: match[2],
            fullPath: path.join(iconDir, svgFile),
          });
        }
      }
    }
  }

  return files;
}

function groupIconsByNameAndCategory(files: SVGFile[]): Map<string, IconEntry> {
  const grouped = new Map<string, IconEntry>();

  for (const file of files) {
    const key = `${file.category}:${file.name}`;
    if (!grouped.has(key)) {
      grouped.set(key, {
        category: file.category,
        name: file.name,
        sizes: [],
      });
    }
    grouped.get(key)!.sizes.push(parseInt(file.size, 10));
  }

  // Sort sizes numerically
  for (const entry of grouped.values()) {
    entry.sizes.sort((a, b) => a - b);
  }

  return grouped;
}

function generateStoryFile(entry: IconEntry): string {
  const sizes = entry.sizes;
  const sizeOptions = sizes.join(', ');
  const defaultSize = sizes[0];
  const categoryName = entry.category.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');

  return `// DO NOT EDIT — generated by scripts/generate-stories.ts
import type { Meta, StoryObj } from '@storybook/react';
import * as Icons from '@gabrieleghio/icons-react';

const meta: Meta = {
  title: '${categoryName}/${entry.name}',
  parameters: {
    layout: 'centered',
  },
  argTypes: {
    size: {
      control: { type: 'select' },
      options: [${sizeOptions}],
    },
    color: {
      control: { type: 'color' },
    },
  },
  args: {
    size: ${defaultSize},
    color: '#1a1a1a',
  },
};

export default meta;

export const Default: StoryObj = {
  render: (args) => {
    const componentName = \`${entry.name}\${args.size}\` as keyof typeof Icons;
    const Component = Icons[componentName] as any;
    return <Component color={args.color} />;
  },
};
`;
}

export function main(rawDir: string = DEFAULT_RAW_DIR, outputDir: string = DEFAULT_OUTPUT_DIR) {
  const svgFiles = getSVGFiles(rawDir);
  const iconsByCategory = groupIconsByNameAndCategory(svgFiles);

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Group by category for directory structure
  const iconsByDir = new Map<string, IconEntry[]>();
  for (const entry of iconsByCategory.values()) {
    const categoryDir = entry.category;
    if (!iconsByDir.has(categoryDir)) {
      iconsByDir.set(categoryDir, []);
    }
    iconsByDir.get(categoryDir)!.push(entry);
  }

  // Generate story files
  for (const [categoryDir, icons] of iconsByDir) {
    const categoryPath = path.join(outputDir, categoryDir);
    if (!fs.existsSync(categoryPath)) {
      fs.mkdirSync(categoryPath, { recursive: true });
    }

    for (const entry of icons) {
      const storyContent = generateStoryFile(entry);
      const storyFile = path.join(categoryPath, `${entry.name}.stories.tsx`);
      fs.writeFileSync(storyFile, storyContent, 'utf-8');
      console.log(`✓ Generated story ${categoryDir}/${entry.name}`);
    }
  }

  console.log(`\n✓ Stories generated: ${iconsByCategory.size} files`);
}

// Only run main if this file is the entry point
if (process.argv[1]?.endsWith('generate-stories.ts')) {
  main();
}
